### ISSUE TITLE
jongo.insert() does not support arrays of documents

### ISSUE THREAD

**Issue by danvarga** [bguerout/jongo#172]
The jongo site says "insert works as in mongo shell".  This isn't 100% true, mongo shell allows for the addition of of multiple documents in an array.

For example:
Mongo cmd that works:

db.metrics.insert([{"group": "swap", "uuid": "12345", "value": 17179860992, "name": "total"}, {"group": "swap", "uuid": "12345", "value": 0.0, "name": "percent"}, {"group": "swap", "uuid": "12345", "value": 0, "name": "used"}, {"group": "swap", "uuid": "12345", "value": 17179860992, "name": "free"}, {"group": "swap", "uuid": "12345", "value": 0, "name": "sin"}, {"group": "swap", "uuid": "12345", "value": 0, "name": "sout"}])

Same object as above as a string fails in the code below:

public void addMetric(String metric) throws Exception {

```
    mongoProvider.getMetricsColl().insert(metric);
```

}

What also doesn't seem to work correctly is trying to insert(List<Metric> metric).  It inserts it as one document with each document embedded within in.

**Comment by shubhampardesi** [comment]
Suppose I am taking 10 Objects of Friend class and insert using above mentioned way, if suppose first 3 are inserted and for 4th , some error are occurred, in that case what happen , all inserted or 0 inserted...what actually happens when multiple transaction is executing on mongo using jongo...
Because mongo doesn't gives this facility...this facility is of jongo ?
