### ISSUE TITLE
Jongo client can only be initialized using deprecated methods of the 3.0 Java driver

### ISSUE THREAD

**Issue by alex-sherwin** [bguerout/jongo#254]
The Jongo client can only be constructed with an instance of `com.mongodb.DB`, and the only way to get an instance of that now using the 3.0 Java driver's `com.mongodb.MongoClient#getDB(String)` deprecated method.

The 3.0 Java driver introduced a new preferred type `com.mongodb.MongoDatabase` which can be accessed via `com.mongodb.MongoClient#getDatabase(String)`

The Jongo driver should be updated to support the Java 3.0 driver without requiring any deprecated code references

**Comment by bguerout** [comment]
You are right. Jongo still relies on the DB class.
Currently we support driver versions 2.13 and 3.0 that work both with MongoDB 3.0.

The new ```com.mongodb.client.MongoDatabase``` class exposes a totally new API with new operation methods (replaceOne, replaceMany). So using MongoDatabase implies to rethink Jongo and its Public API.

BTW i'm a bit uncomfortable with this new driver API because the driver exposes methods (eg. insertMany) that doesn't exist in MongoDB. So the Jongo's slogan "Querying in java as in Mongo Shell" seems to be harder to code (see #255).
May be we can just provide tools to help user to user new driver API.

**Comment by paulovictorv** [comment]
In my opinion, Jongo's most valuable feature is to be able to write queries in pure BSON and not worry about building complicated QueryObject's. If Jongo is able to stick to that, but changing the API to expose more methods from the underlying driver, I think that's fine.

I think that Jongo should not limit itself on the Mongo shell API. If we think as programmers and not just shell users, we would like to have advanced features that the pure shell cannot provide, such as async interactions and so on.

Anyways, that's my opinion. I've been using Jongo for over a year now in multiple projects, and I want to see it evolve beyond the Shell. I'm able to contribute with code, also.

**Comment by alex-sherwin** [comment]
You'll also run the risk of becoming obsolete.  The 2.x driver line will surely fall out of favor in the coming year or two and if Jongo is still reliant on 2.x deprecated methodologies then it will fall eventually fall out of favor itself.

I like Jongo a lot, and don't want to see that happen .. It's not an immediate issue, but I think that if Jongo is going to survive long term it will have to adapt to utilize the 3.0 driver

**Comment by diogogmt** [comment]
Another Jongo user here as well. We've been using Jongo in a few internal projects and recently we were updating mongo to version 3 and just noticed that Jongo would not work with the native java driver 3.x

I'm not sure who's the official maintainer of the project and if an update to support the 3.x drivers are on the way but if I can get a confirmation that if a patch would be submitted it would be accepted I believe we could try to contribute something.

**Comment by bguerout** [comment]
Hello, 
Pull requests are welcomed.
Do not hesitate to init a pull-request with a not yet finished implementation (This allows to discuss early about the refactoring)

**Comment by diogogmt** [comment]
@bguerout that sounds good.
I'll try to send the initial pr by next week so we can get it rolling.

**Comment by bguerout** [comment]
Cool

**Comment by julienlavergne** [comment]
Ok I discover this feed.
 
not any PR ?

**Comment by diogogmt** [comment]
@julienlavergne 
We had started an initial integration of the new MongoDB Java driver 3.0.3 with Jongo but it is not completed yet.
We're hoping to have that patch ready soon.

**Comment by julienlavergne** [comment]
@diogogmt Oh I am going to implement this part. thanks for this information. I will be waiting for the next release.

**Comment by julienlavergne** [comment]
@diogogmt Oh I am going to implement this part. thanks for this information. I will be waiting for the next release.

Any date to communicate? ;)

**Comment by diogogmt** [comment]
@julienlavergne 

Have you started working on a patch already?
I'll try to open a PR with at least a skeleton patch to get some feedback. I should have some time to work on the patch over this weekend.

**Comment by julienlavergne** [comment]
Sorry I had this dream but no time for this really.

If you open a PR, I could participate.

-- 
Julien Lavergne
Sent with Airmail

On August 19, 2015 at 5:30:12 PM, Diogo Monteiro (notifications@github.com) wrote:

@julienlavergne

Have you started working on a patch already?
I'll try to open a PR with at least a skeleton patch to get some feedback. I should have some time to work on the patch over this weekend.

**Comment by diogogmt** [comment]
The patch is still on my TODO list but I won't be able to get to it anytime soon.
If anybody else have some time please go ahead.

**Comment by julienlavergne** [comment]
Can you push on a branch your work ?

-- 
Julien Lavergne
+33670273883
http://julienlavergne.com
Sent with Airmail

On September 10, 2015 at 1:57:47 PM, Diogo Monteiro (notifications@github.com) wrote:

The patch is still on my TODO list but I won't be able to get to it anytime soon.
If anybody else have some time please go ahead.

**Comment by froginvasion** [comment]
Any updates on this?

**Comment by julienlavergne** [comment]
One answer will be appreciated but needs time

Any fork?

--
Julien Lavergne
+33670273883
http://julienlavergne.com

**Comment by diogogmt** [comment]
We switched libraries at work so this patch went down on our priority list.
I don't have anything to share at this moment.

**Comment by bguerout** [comment]
Hello, which mongo library are you using now ?

**Comment by zhengshencn** [comment]
Can I vote for this bug? :)
I just hope it won't be dropped from 1.3.

**Comment by julienlavergne** [comment]
I just hope to have some new constructors to support new mongodb 3 classes.

--
Julien Lavergne
+33670273883
http://julienlavergne.com

**Comment by paulovictorv** [comment]
I started refactoring all of Jongo's API to use the new driver API in #287.

Comments and critics are appreciated.

**Comment by julienlavergne** [comment]
Good news.

@bguerout you can manage this in the next version?

**Comment by jonnywang** [comment]
waiting for migration to use new driver

**Comment by bguerout** [comment]
Four years ago Jongo was created to provide a thin layer over the 2.X API to allow user to query in Java as in Mongo shell with un/marshalling capabilities. 
Lot of classes has been created to circumvent 2.X limitations and public API has exposed methods to provide missing features.

Nowadays 3.X driver provides an API that is better than the previous one and can be used directly.
Nevertheless Jongo is not dead because it is stil not possible to query with string and un/mashall with jackson out-of-the-box.

So I believe that it's better to provide helper methods instead of fully rebuilding Jongo.
Few hours were enough to create a viable implementation versus my attempts to rebuild all which was always aborted due to a "OMG everything is broken".
It will allow progressive client migration from "Jongo + Driver 2.X" to "Driver 3.X + Jongo" without breaking backward compatibility.

A new branch has been created with work in progress implementation https://github.com/bguerout/jongo/tree/codec

```java
@Test
public void jongoV3Example() throws Exception {

    //Get database instance from new driver API
    MongoDatabase database = mongoClient.getDatabase("test_jongo"); 

    //Add Jongo capabililities to new MongoCollection (query, jackson)
    JongoApi jongo =  Jongo.with(database, mapper);
    com.mongodb.client.MongoCollection<Friend> friends = jongo.getCollection("friends", Friend.class);

    Friend friend = new Friend("Robert");

    // Use the Jackson configuration provided by Jongo with new driver methods.
    // No need to change your POJOs
    friends.insertOne(friend);

    //Write query just like before
    Friend robert = collection.find(jongo.query("{name:'#'}", "Robert")).first();
    ...
}
```
Does it sounds good to you ?

**Comment by bguerout** [comment]
You can find working examples here https://github.com/bguerout/jongo/tree/codec/src/test/java/org/jongo/v3

**Comment by yamsellem** [comment]
Hey @bguerout, this is a !!! great idea ^^.
Isolating the difference in a `JongoApi` class seems perfect to me.

Is there a way to offer the same constructor to create a `Jongo` instance and a `JongoApi` one?
Like:

```java
MongoDatabase database = mongoClient.getDatabase("test_jongo"); 
JongoApi jongo =  new Jongo(database, mapper);
```

This may use the evil `instanceOf` in the constructor, but, if it's restricted to that, it may be an advantage to have a one way backward compatible instance creator.

Firstly it seems nice to me to have an interface that share `Jongo` and `JongoApi` behavior, but, after walking through the code, they seem to much different to have any sort of interest. So maybe just a combo would do the trick.

Obviously, if you find it add some value and don't mislead people ;-).

**Comment by bguerout** [comment]
Hi,

'JongoApi' and 'with' are probably just temporary names before finding something better. 
JongoNative seems ok:-)

Unfortunately i think we can no longer use Jongo class because it needs a deprecated DB instance. We can still expose another constructor but it will lead to NullPointerException when a legacy method (eg. getCollection) is called with a Jongo instance created with the new constructor.

The static method 'with' (or wrap or from...) allows the Jongo class to be still the API entry point.

**Comment by yamsellem** [comment]
@bguerout agreed ;-). What's about `Jongo.native(..., ...)` that will return a `JongoNative` instance?

**Comment by reyesr** [comment]
Hi all, my two cents:
- The value of of jongo is not only as a mapper, it's also a wrapper and a useful abstraction that hides any change at the java drivers level. With a set of helpers and calling directly the java driver's MongoCollection, we're unfortunately losing that. Of course, it's great to have anyway because it would allow upgrading with minor work.
- The getDB() API is deprecated but will stay for all the versions 3.x of the driver, and there is not even a 4.x in the roadmap, so you don't have to take a hasty decision (even if there is some user pressure for this upgrade). See https://jira.mongodb.org/browse/JAVA-1858
- If a future version of jongo changes drastically its api, I suggest going for another name, or a variation on the current name, to avoid the painful search-engine experience that comes when a library changes its API yet keeps its name (remember play 2, jackson 2, cglib 3, etc etc it was such a mess when looking for examples or issues). Calling it JongoNative or something instead of plain Jongo may be a good work-around.

**Comment by bguerout** [comment]
@yamsellem native is a keyword so i have renamed it 'useNative()'

**Comment by bguerout** [comment]
@reyesr thanks for the link, i was not aware of that. So user can still use legacy Jongo constructor with driver 3+. That's a good news.

I totally agree with you about project renaming rules.

**Comment by bguerout** [comment]
Native API has been merged into master and should be released in v1.4.0

**Comment by shetc** [comment]
Hi All -- I have been researching data access frameworks to use with mongodb, and I quite the looks of Jongo. I can't quite tell from this discussion how Jongo will be moving forward. Is the 1.3.0 version safe to use with mongodb 3.x drivers? Or should I wait for the 1.4 version? Thanks, Steve

**Comment by ctrimble** [comment]
@shetc I am in the middle of upgrading some applications from Mongo 2.6.4 to 3.2.6.  All of my integration tests are passing against both versions of Mongo, using Jongo 1.3.0 and Mongo Java Driver 3.2.2.  The only change I had to make were related to the creation of credentials.  Instead of using `MongoCredential.createMongoCRCredential` to build credentials, I had to use 'MongoCredential.createCredential`.

**Comment by shetc** [comment]
Thanks for the response,  Christian! I have to make a business decision soon, and I want to be sure there is forward path for Jongo. Steve

**Comment by bguerout** [comment]
@shetc , yes you can use 1.3.0 with mongodb 3.x drivers. 

BTW we have a CI job to test Jongo against multiple driver versions and Mongo 2.6/3+ : https://jongo.ci.cloudbees.com/job/jongo-test-mongo-versions
Here is the results of the last execution : 
```
Running tests against java driver 3.0.1 and MongoDB 2.6
3.0.1 SUCCESS
Running tests against java driver 3.0.2 and MongoDB 2.6
3.0.2 SUCCESS
Running tests against java driver 3.0.3 and MongoDB 2.6
3.0.3 SUCCESS
Running tests against java driver 3.0.4 and MongoDB 2.6
3.0.4 SUCCESS
Running tests against java driver 3.0.5-SNAPSHOT and MongoDB 2.6
3.0.5-SNAPSHOT SUCCESS
Running tests against java driver 3.1.0 and MongoDB 2.6
3.1.0 SUCCESS
Running tests against java driver 3.1.0-rc0 and MongoDB 2.6
3.1.0-rc0 SUCCESS
Running tests against java driver 3.1.1 and MongoDB 2.6
3.1.1 SUCCESS
Running tests against java driver 3.2.0 and MongoDB 2.6
3.2.0 SUCCESS
Running tests against java driver 3.2.0-rc0 and MongoDB 2.6
3.2.0-rc0 SUCCESS
Running tests against java driver 3.2.1 and MongoDB 2.6
3.2.1 SUCCESS
Running tests against java driver 3.2.2 and MongoDB 2.6
3.2.2 SUCCESS
Running tests against java driver 3.3.0-SNAPSHOT and MongoDB 2.6
3.3.0-SNAPSHOT SUCCESS
-------------------------------
Running tests against java driver 3.0.1 and MongoDB 3.0
3.0.1 SUCCESS
Running tests against java driver 3.0.2 and MongoDB 3.0
3.0.2 SUCCESS
Running tests against java driver 3.0.3 and MongoDB 3.0
3.0.3 SUCCESS
Running tests against java driver 3.0.4 and MongoDB 3.0
3.0.4 SUCCESS
Running tests against java driver 3.0.5-SNAPSHOT and MongoDB 3.0
3.0.5-SNAPSHOT SUCCESS
Running tests against java driver 3.1.0 and MongoDB 3.0
3.1.0 SUCCESS
Running tests against java driver 3.1.0-rc0 and MongoDB 3.0
3.1.0-rc0 SUCCESS
Running tests against java driver 3.1.1 and MongoDB 3.0
3.1.1 SUCCESS
Running tests against java driver 3.2.0 and MongoDB 3.0
3.2.0 SUCCESS
Running tests against java driver 3.2.0-rc0 and MongoDB 3.0
3.2.0-rc0 SUCCESS
Running tests against java driver 3.2.1 and MongoDB 3.0
3.2.1 SUCCESS
Running tests against java driver 3.2.2 and MongoDB 3.0
3.2.2 SUCCESS
Running tests against java driver 3.3.0-SNAPSHOT and MongoDB 3.0
3.3.0-SNAPSHOT SUCCESS
```

If you prefer to start with the new native API (the one which not rely on a deprecated class), you can test this beta version
```xml
<dependencies>
  <dependency>
    <groupId>org.jongo</groupId>
    <artifactId>jongo</artifactId>
    <version>jongo-1.4-early-20160606-0118</version>
  </dependency>
</dependencies>
...
<repositories>
    <repository>
       <id>cloudbees-jongo-early-release</id>
        <url>http://repository-jongo.forge.cloudbees.com/release</url>
        <releases>
            <enabled>true</enabled>
        </releases>
        <snapshots>
            <enabled>false</enabled>
        </snapshots>
    </repository>
</repositories>
```
**Note that this version must be considered as a beta of the future 1.4.0 release**

**Comment by kno10** [comment]
How does the performance of the native API version compare?

**Comment by orangecoding** [comment]
I'm having a big(!) project ahead and was thinking about which mongo driver / simplification we should use. Jongo seemed to be a good lightweight solution.. However, this problem is open since 2015 which leaves me with the question whether or not this lib is actively maintained..?
Don't get me wrong, no pressure, just want to check the status and whether or not you guys think this will be fixed in the near future

**Comment by bguerout** [comment]
Yes this is still maintained. I'm trying to spend some time this month on this project. I'm in the process of releasing the versions 1.3.1 and 1.4.0.
Then will come the 1.5.0 with the new API (mongo-java-driver 3+)

See https://github.com/bguerout/jongo/milestones for more informations
