### ISSUE TITLE
named parameters

### ISSUE THREAD

**Issue by chen56** [bguerout/jongo#54]
Supports named parameters , jpql example:
SELECT pub FROM Publisher pub WHERE pub.revenue>: rev

jongo :
friends.find("{name: #name, age: #age}")
  .bind("name","John")
  .bind("age",18)
;

**Comment by netbrain** [comment]
:+1: would be great when using the same parameter for several fields

**Comment by froginvasion** [comment]
Since I needed this, I wrote this functionality for my own project. To point an idea how to do this: I wrote

**Comment by froginvasion** [comment]
Since I needed this, I implemented this functionality myself. Thanks to the nice codebase of Jongo, this was possible (unlike to use Spring data mongodb's parameter substitution). To point to an implementation idea:

I made a wrapper around `BsonQueryFactory`, which ultimately does the query substitution. Then, I loop over all named parameters (expecting only named parameters though!), and keep that in a list. I remove the parameter names, so I convert it to the format Jongo expects. I then keep a list with the bindings of the parameters themselves (the values). When all parameters are set, I use the BsonQueryFactory to build the query, and supply the bound values.
